### ISSUE TITLE
TPAC 2024 Planning 

### ISSUE THREAD

**Issue by wareid** [w3c/pm-wg#5]
We will be meeting at TPAC 2024 in Anaheim, California. What do we want to discuss?

**Comment by wareid** [comment]
Discussed with Publishing steering committee: 
- Potential workshop on EAA and what publishing is doing? 
- EAA, changes to US DOJ rulings

From the group: 
- scrolled contents (web toons) 
- time to publish the errata?
- CG/WG topics: (format agnostic, EPUB and Pub Manifest)
  - shared annotations
  - locators (related to annotations)
  - TTS (potentially joint meeting with other working/community groups?)
  - anti-counterfeiting, TDM, signing of EPUB documents (not DRM), workflow identifiers 
  - Audiobooks accessibility

**Comment by wareid** [comment]
Potential other groups to meet with? 
- Federated Identifiers / Verifiable Credentials 
- TTS:
  - TTML 
  - ARIA
  - Léonie / WICG (would anyone be interested)
  - Markku H.

**Comment by bduga** [comment]
We have effectively tied our hands with the existing charter, can we
discuss ways to make substantive changes to EPUB going forward?

**Comment by TzviyaSiegman** [comment]
Moving EPUB forward (beyond backward compat) /cc @bduga

**Comment by gregoriopellegrino** [comment]
Is this the proposal agenda for the Working Group meeting or for the public event?

**Comment by bduga** [comment]
What public event? Sorry, I am a little behind the times.

**Comment by TzviyaSiegman** [comment]
@gregoriopellegrino This is for the WG. We are not doing a public event. We will invite members of the BG (and possibly CG) to participate in the meeting.

**Comment by dalerrogers** [comment]
Will members of this group be permitted to join remotely? I'd like to attend the session on fixed-layout.

**Comment by iherman** [comment]
> Will members of this group be permitted to join remotely? I'd like to attend the session on fixed-layout, and or web-toons.

Yes. Each meeting room will be equipped with a Zoom enabled device, and a zoom reference will be available for all participants.
